//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralSecurityProject.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentralSecurityProject.Models.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Id.
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Resource Id.
        /// </summary>
        public static string AppResourceId {
            get {
                return ResourceManager.GetString("AppResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Resource No.
        /// </summary>
        public static string AppResourceNo {
            get {
                return ResourceManager.GetString("AppResourceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Name.
        /// </summary>
        public static string ControlName {
            get {
                return ResourceManager.GetString("ControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert Date.
        /// </summary>
        public static string ExpertDate {
            get {
                return ResourceManager.GetString("ExpertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string ExpertId {
            get {
                return ResourceManager.GetString("ExpertId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert Name.
        /// </summary>
        public static string ExpertUsername {
            get {
                return ResourceManager.GetString("ExpertUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Id.
        /// </summary>
        public static string OperationId {
            get {
                return ResourceManager.GetString("OperationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation No.
        /// </summary>
        public static string OperationNo {
            get {
                return ResourceManager.GetString("OperationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference App Resource Id.
        /// </summary>
        public static string RefAppResourceId {
            get {
                return ResourceManager.GetString("RefAppResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Operation Id.
        /// </summary>
        public static string RefOperationId {
            get {
                return ResourceManager.GetString("RefOperationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Description.
        /// </summary>
        public static string RequestDescription {
            get {
                return ResourceManager.GetString("RequestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request History Date.
        /// </summary>
        public static string RequestHistoryDate {
            get {
                return ResourceManager.GetString("RequestHistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Num.
        /// </summary>
        public static string RequestId {
            get {
                return ResourceManager.GetString("RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status Id.
        /// </summary>
        public static string RequestStatusId {
            get {
                return ResourceManager.GetString("RequestStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string RequestStatusName {
            get {
                return ResourceManager.GetString("RequestStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type Id.
        /// </summary>
        public static string RequestTypeId {
            get {
                return ResourceManager.GetString("RequestTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string RequestTypeName {
            get {
                return ResourceManager.GetString("RequestTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Username.
        /// </summary>
        public static string RequestUsername {
            get {
                return ResourceManager.GetString("RequestUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Description.
        /// </summary>
        public static string ResourceDesc {
            get {
                return ResourceManager.GetString("ResourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Id.
        /// </summary>
        public static string ResourceId {
            get {
                return ResourceManager.GetString("ResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Name.
        /// </summary>
        public static string ResourceName {
            get {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Code.
        /// </summary>
        public static string RoleCode {
            get {
                return ResourceManager.GetString("RoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Id.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
