//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centeral Security System.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartblock Panel.
        /// </summary>
        internal static string CartblockPanel {
            get {
                return ResourceManager.GetString("CartblockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define App Group.
        /// </summary>
        internal static string DefineAppGroup {
            get {
                return ResourceManager.GetString("DefineAppGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define App Resource.
        /// </summary>
        internal static string DefineAppResource {
            get {
                return ResourceManager.GetString("DefineAppResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define App User.
        /// </summary>
        internal static string DefineAppUser {
            get {
                return ResourceManager.GetString("DefineAppUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Parameters System.
        /// </summary>
        internal static string DefineParamSystem {
            get {
                return ResourceManager.GetString("DefineParamSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Request Status.
        /// </summary>
        internal static string DefineRequestStatus {
            get {
                return ResourceManager.GetString("DefineRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Request Type.
        /// </summary>
        internal static string DefineRequestType {
            get {
                return ResourceManager.GetString("DefineRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Role.
        /// </summary>
        internal static string DefineRole {
            get {
                return ResourceManager.GetString("DefineRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define System.
        /// </summary>
        internal static string DefineSystem {
            get {
                return ResourceManager.GetString("DefineSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define System Group.
        /// </summary>
        internal static string DefineSystemGroup {
            get {
                return ResourceManager.GetString("DefineSystemGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Users.
        /// </summary>
        internal static string DefineUsers {
            get {
                return ResourceManager.GetString("DefineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departement.
        /// </summary>
        internal static string Departement {
            get {
                return ResourceManager.GetString("Departement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi.
        /// </summary>
        internal static string Farsi {
            get {
                return ResourceManager.GetString("Farsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated System.
        /// </summary>
        internal static string IntegratedSystem {
            get {
                return ResourceManager.GetString("IntegratedSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Check.
        /// </summary>
        internal static string NotCheck {
            get {
                return ResourceManager.GetString("NotCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral.
        /// </summary>
        internal static string Referral {
            get {
                return ResourceManager.GetString("Referral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Request.
        /// </summary>
        internal static string ReferralRequest {
            get {
                return ResourceManager.GetString("ReferralRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        internal static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Application.
        /// </summary>
        internal static string SearchApplication {
            get {
                return ResourceManager.GetString("SearchApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Request.
        /// </summary>
        internal static string SubmitRequest {
            get {
                return ResourceManager.GetString("SubmitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephon.
        /// </summary>
        internal static string Telephon {
            get {
                return ResourceManager.GetString("Telephon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreferral.
        /// </summary>
        internal static string Unreferral {
            get {
                return ResourceManager.GetString("Unreferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserLogin.
        /// </summary>
        internal static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define users.
        /// </summary>
        internal static string XDefineUser {
            get {
                return ResourceManager.GetString("XDefineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define users to access the programs in the comprehensive system.
        /// </summary>
        internal static string XDefineUserDesc {
            get {
                return ResourceManager.GetString("XDefineUserDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define resources.
        /// </summary>
        internal static string XResourceDefinition {
            get {
                return ResourceManager.GetString("XResourceDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define access sources to access program resources.
        /// </summary>
        internal static string XResourceDefinitionDesc {
            get {
                return ResourceManager.GetString("XResourceDefinitionDesc", resourceCulture);
            }
        }
    }
}
